version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:8000
    container_name: portfolio_app
    # depends_on:
    #   - api
  # api:
  #   build: ./server
  #   volumes:
  #     - ./server:/api
  #     - /api/node_modules
  #   ports:
  #     - 3000:3000
  #   container_name: portfolio_api